import React from "react";

export class TermsAndConditionsMarkup extends React.Component {
	render(){
		return(
			<div className={"font--bodycopy general " + this.props.sendGeneral} style={{paddingBottom: "10em"}}>
				<div className="padding--1em">
					<p><strong>1. Introduction</strong></p>
					<p><strong>1.1.</strong> The following terms and conditions ("Terms of Usage") shall govern your use of AEON Credit Service (M) Berhad&rsquo;s AEON Wallet application ("AEON Wallet") using a compatible and supported Device (as defined in Section 11 herein). These Terms of Usage form a legal agreement that is binding between you and AEON Credit Service (M) Berhad ("AEON Credit" or "the Company") when you download, activate and/or use the AEON Wallet, including enhancements and new versions made available in the future.</p>
					<p><strong>1.2.</strong> In addition to these Terms of Usage, you also agree to comply with and adhere to the Terms &amp; Conditions of the following agreements (whichever applicable): </p>
					<p>(a) the AEON Credit Card* Cardholder Agreement; </p>
					<p>(b) the AEON Prepaid Card* Cardholder Agreement;</p>
					<p>(c) the customer agreement for loyalty programme/membership card issued by or for AEON Group of Companies in Malaysia (whichever applicable); and </p>
					<p>(d) the terms and conditions of any other document or agreement governing your relationship with us, including Easy Payment and Personal Financing agreements, if any. </p>
					<p><em>(*</em><strong><em>Note:</em></strong><em> Including various types of credit cards and prepaid cards issued by ACSM)</em></p>
					<p><strong>2. AEON Wallet</strong></p>
					<p><strong>2.1. AEON Wallet Application Software (&ldquo;the Application&rdquo;)</strong></p>
					<p><strong>2.1.1.</strong> In order to use the AEON Wallet, you are required to download the application software from Google Playstore or Apple Store to your Device, and thereafter register the AEON Wallet with AEON Credit through the application. </p>
					<p><strong>2.1.2.</strong> AEON Credit is not responsible or liable in any way for your access to the Google Playstore and Apple Store. You are solely responsible for the installation, configuration or compatibility of the hardware, software and other equipment used for installation of the AEON Wallet application on your Device. </p>
					<p><strong>2.2. Your Responsibilities </strong></p>
					<p><strong>2.2.1.</strong> You agree to register for the AEON Wallet and provide true, accurate, current and complete information as prompted by AEON Wallet's registration form ("Registration Data"). If you provide any information that is untrue, inaccurate, not current or incomplete, or if AEON Credit has reasonable grounds to believe that any information is untrue, inaccurate, not current or incomplete, AEON Credit has the right to suspend or terminate your access to AEON Wallet and refuse any and all current or future use of AEON Wallet (or any part thereof) without any liability. </p>
					<p><strong>2.2.2.</strong> You shall ensure the compatibility of your mobile device with AEON Wallet. In the event that changes and upgrades are introduced to AEON Wallet, you shall be responsible to ensure the continued compatibility of your Device and you shall have no claim whatsoever against AEON Credit arising therefrom.</p>
					<p><strong>2.2.3.</strong> You shall be responsible for any Device, software and mobile network/data services necessary to use AEON Wallet and also for ensuring accuracy of information or transaction data submitted or confirmed by you through the use of the AEON Wallet; and</p>
					<p><strong>2.2.4</strong> You shall not install the Application on a jail-broken or rooted Device. Unauthorised modifications to any Device(s) operating systems ("jail-breaking or rooting") bypass security features and can cause numerous issues to the hacked devices; thus such Device(s)are vulnerable to fraudulent attacks and may expose your Account(s) registered under AEON Wallet being used by unauthorised persons, whether remotely performed or otherwise.</p>
					<p><strong>2.2.5.</strong> You shall be solely responsible for all fees and charges related to access and connection to the AEON Wallet including but not limited to phone/telecommunication usage, mobile data usage charges and any other charges imposed by any Network/Wifi Service Provider.</p>
					<p><strong>2.2.6.</strong> Your AEON Wallet cannot be transferred and you must be the individual holding the NRIC or passport number registered with AEON Credit. </p>
					<p><strong>2.2.7</strong> You are responsible for maintaining the confidentiality of the PIN for the Application, and you shall be fully responsible for all activities/transactions made with your PIN or Account. AEON Credit will not be liable for any loss or damage arising from your failure to take reasonable steps to maintain the confidentiality of your Account or PIN, your failure to exit from the Application immediately upon ceasing to using the Application for any transaction or enquiry, or your negligence in safeguarding/securing Device against loss or theft. </p>
					<p><strong>2.3.</strong> <strong>Use of AEON Wallet </strong></p>
					<p><strong>2.3.1.</strong> By installing the Application, you represent and warrant that you are the person holding the relevant credit card, prepaid card, loyalty programme/membership or other account with AEON Credit to be enrolled for utilisation in the AEON Wallet.</p>
					<p><strong>2.3.2.</strong> By using the Application, you agree and undertake to use the Application functions in accordance with these Terms of Usage, and accept the risk that by enabling the Application on your Device, unauthorised access may arise using your login information, and you will be liable solely for all information accessed or transactions performed by any other person without your knowledge, authority or consent. </p>
					<p><strong>2.3.3. </strong>References to material and information contained on AEON Wallet include such material and information provided by third parties. AEON Credit does not make any express or implied warranties including but not limited to any warranties of title, non-infringement, merchantability, usefulness, operation, completeness, currency, accuracy, satisfactory quality, reliability, fitness for a particular purpose in respect of such material, information and/or functions therein. </p>
					<p><strong>2.3.4.</strong> You understand and agree that the AEON Wallet is provided on "As-Is Basis" and that AEON Credit assumes no responsibility for your inability to access/use the AEON Wallet or any part thereof, the rejection of your transactions, the incorrect processing of your transactions as a result of your failure to maintain your account with the Network/Wifi Service Provider or your failure to obtain or use the necessary application version, Device(s), internet browser and/or other hardware and/or software including but not limited to any failure to upgrade the relevant operating system and/or software or to use the new and recent versions of the same as may be required by AEON Credit.</p>
					<p><strong>2.3.5.</strong> AEON Credit does not warrant that access to the whole or part(s) of AEON Wallet, the materials, information and/or the functions contained therein will be provided uninterrupted or free from errors or that there will be no delays, failures, errors or loss of transmitted information, that no viruses or other contaminating or destructive properties will be transmitted or that no damage will occur to your Device. </p>
					<p><strong>2.3.6.</strong> Without limiting the above and/or the terms and conditions of the applicable agreements governing all the products and services of AEON Credit, reasonable measures will nevertheless be taken by the Company to ensure the integrity of systems and processes as well as timely processing of transactions and information requests related to services offered by the Company through the AEON Wallet. </p>
					<p><strong>2.3.7. </strong>The materials, information and functions provided shall not under any circumstances be considered or construed as an offer or solicitation to sell, buy, give, take, issue, redeem or transfer, or as the giving of any advice in respect of loans, advances, credits or easy payment products in any jurisdiction. You shall be responsible to evaluate the quality, adequacy, completeness, currency and usefulness of all services, content, advice, opinions and other information obtained or accessible through AEON Wallet. </p>
					<p><strong>2.3.8</strong> While there are no charges currently imposed by AEON Credit for installation and usage of AEON Wallet, the Company may in the future impose fees/charges for AEON Wallet (or service(s) under AEON Wallet) at any time, at its sole discretion by providing prior notice to you in accordance with Clause 8.2.1.</p>
					<p><strong>3. AEON Pay</strong></p>
					<p><strong>3.1. Eligibility of AEON Pay </strong></p>
					<p><strong>3.1.1.</strong> You may enroll your payment card(s) and/ or loyalty programme/membership card(s) (&ldquo;Card&rdquo;) and store them electronically in the AEON Wallet. You may use the Device to make contactless payments using AEON Pay function and obtain loyalty programme/membership recognition to earn/redeem reward points etc. </p>
					<p><strong>3.1.2.</strong> The AEON Pay function can be used for contactless payments via Quick Response Code (&ldquo;QR Code&rdquo;) technology at participating merchants for amounts not exceeding your Credit Limit (as defined in the AEON Credit Card Cardholder Agreement), Stored Value (as defined in the AEON Prepaid Card Cardholder Agreement) or other limit as notified to you by the Company from time to time at the Company&rsquo;s sole and absolute discretion.</p>
					<p><strong>3.1.3.</strong> By using the AEON Pay for payments, you accept the risk that unauthorised payment transactions may be made using AEON Pay on your Device (linked to your Card information), and you will be solely liable for all such payment transactions, notwithstanding that your Device or PIN may have been used by any other person without your knowledge, authority or consent. </p>
					<p><strong>3.1.4.</strong> The usage of AEON Pay is limited to the Device associated with the mobile phone number registered with AEON Credit for your credit card, prepaid card or other ACSM product that you are currently using. </p>
					<p><strong>3.2 Use of AEON Pay</strong></p>
					<p><strong>3.2.1. </strong>You may enroll one or more Cards in your AEON Wallet in accordance with the procedures notified by AEON Credit. You shall also be required to create a PIN and/or register your fingerprint on the Device to enable access to the AEON Wallet, and you shall be deemed to have agreed to this Terms of Usage each time you enroll a Card on your Device.</p>
					<p><strong>4. Security of AEON Wallet and AEON Pay</strong></p>
					<p><strong>4.1.</strong> You must: </p>
					<p>(a) keep the PIN and any other login or access information on your Device secret and confidential at all times; </p>
					<p>(b) safeguard and secure the Device at all times times to prevent fraudulent or unauthorised access to or use of AEON Wallet and AEON Pay; and</p>
					<p>(c) take all reasonable steps to lock/disable the use of AEON Wallet and AEON Pay immediately upon being aware of unauthorised usage, loss or theft of Device.</p>
					<p><strong>4.2.</strong> You must report to the Company as soon as you:- </p>
					<p>(a) suspect or become aware that the Device is lost or stolen; </p>
					<p>(b) suspect or become aware that the mobile PIN has or may have been disclosed to another person; or </p>
					<p>(c) suspect or become aware that there has been unauthorised use of PIN or Device. </p>
					<p><strong>4.3.</strong> In the event of any loss, theft or disclosure of the PIN or Device, you are responsible for all transactions made by anyone using the AEON Wallet or AEON Pay until AEON Credit is notified or action has been taken by you to lock/disable the AEON Wallet. You will be bound by the existing terms and conditions of your physical cards issued by AEON Credit, including your liability for unauthorised transactions.</p>
					<p><strong>4.4.</strong> In the event you change your Device, the AEON Wallet access on the old Device shall be locked/disabled by you immediately based on procedures notified by AEON Credit. </p>
					<p><strong>5. Intellectual Property</strong></p>
					<p><strong>5.1 Ownership</strong></p>
					<p><strong>5.1.1.</strong> The Intellectual Property in and to the AEON Wallet and AEON Pay are owned, licensed to or controlled by the Company, our licensors or our service providers (where applicable). The Company reserves the right to enforce its Intellectual Property Rights as defined herein to the fullest extent of the law.<br /> <br /> <strong>5.1.2.</strong> &ldquo;Intellectual Property Rights&rdquo; as used in these Terms of Usage include, both in Malaysia and throughout the world, any copyright, trade mark, service mark, design, patent, patent applications, or other proprietary right, or any right to registration of such rights.</p>
					<p><strong>5.2. Restricted Use</strong></p>
					<p><strong>5.2.1.</strong> No part or parts of AEON Wallet and AEON Pay may be reproduced, reverse engineered, decompiled, disassembled, separated, altered, distributed, republished, displayed, broadcast, hyperlinked, mirrored, framed, transferred or transmitted in any manner or by any means or stored in an information retrieval system or installed on any server, system or equipment without the Company&rsquo;s prior written permission or prior written permission from the relevant copyright owners. </p>
					<p><strong>5.3. Trademarks</strong></p>
					<p><strong>5.3.1.</strong> Nothing in these Terms and Conditions shall be construed as granting, by implication, estoppel, or otherwise, any license or right to use any trademarks displayed or assignment of an Intellectual Property Right in respect of AEON Wallet or AEON Pay (as the case may be), without the Company&rsquo;s written permission (or that of any other applicable trademark owner, as may be relevant). </p>
					<p><strong>6. Disclaimer and Exclusion of Liability </strong></p>
					<p><strong>6.1.</strong> You expressly agree that access and use of AEON Wallet and AEON Pay is at your sole risk. The Company hereby excludes and disclaims all warranties and conditions, either express, implied or statutory, including but not limited to, the implied warranties or conditions of merchantability, satisfactory quality, fitness for a particular purpose, accuracy, and non-infringement of third party rights. </p>
					<p><strong>6.2</strong>. The Company also does not warrant against interference with your enjoyment, that the functions or services performed or provided by AEON Wallet will meet your requirements, that the operation or availability of AEON Wallet and AEON Pay will be uninterrupted or error-free, or that the AEON Wallet and AEON Pay shall be free from errors and defects. </p>
					<p><strong>6.3.</strong> In addition to the other terms, the Company is not liable for any direct, indirect, incidental, punitive, special or consequential damages or economic losses whatsoever or howsoever caused arising directly or indirectly in connection with poor or interrupted mobile network coverage. </p>
					<p><strong>7. Indemnity </strong></p>
					<p><strong>7.1. </strong>You agree to hold the Company harmless and indemnify the Company and all its employees, nominees, directors, licensors, sponsors, affiliates and agents for any losses and embarrassment suffered by the Company (other than such loss and embarrassment arising from the Company or its employees' and agents' willful misconduct or gross negligence) from any claim or demand, including reasonable legal fees, made by a third party due to or in connection with your installation, access and/or use of the AEON Wallet or AEON Pay.</p>
					<p><strong>8. General </strong></p>
					<p><strong>8.1. Waiver </strong></p>
					<p>Any failure or delay by the Company in exercising or enforcing any right the Company has under these Terms of Usage does not operate as a waiver of and does not prejudice or affect the Company&rsquo;s right subsequently to act strictly in accordance with the Company&rsquo;s rights. </p>
					<p><strong>8.2. Variation </strong></p>
					<p><strong>8.2.1.</strong> You agree that these Terms of Usage may be changed from time to time. If the Company changes or adds any term or condition to these Terms of Usage, the Company will provide you with 21 days prior notice and the change or addition will take effect on the date specified in the notice. </p>
					<p><strong>8.2.2.</strong> You agree that your continued use of the AEON Wallet after such update will constitute the acceptance of an agreement to be bound by the updated Terms of Usage. </p>
					<p><strong>8.2.3.</strong> If you do not accept the change or addition to these Terms of Usage, you must stop accessing and using the AEON Wallet and terminate your access and use of the AEON Wallet or AEON Pay. If you continue to access and use the AEON Wallet after the change or addition takes effect, you will be deemed to have accepted the revised Terms of Usage without reservation. </p>
					<p><strong>8.3. Severability </strong></p>
					<p>If any of these Terms and Conditions is rendered invalid, unlawful or unenforceable under the laws of Malaysia, it shall not affect or impair the validity, legality or enforceability of the rest of the terms.</p>
					<p><strong>8.4. Illegality </strong></p>
					<p>AEON Credit may close and revoke any access and or service with or without notice to you if, because of any change to any applicable law, regulation, regulatory requirement or judicial decision, or in our opinion, maintaining or performing any obligation under these Terms of Usage becomes illegal, or we are otherwise prohibited from doing so.</p>
					<p><strong>8.5. Assignment </strong></p>
					<p><strong>8.5.1.</strong> These Terms of Usage are binding on you and on the Company and on respective successors-in-title and/or permitted assigns. </p>
					<p><strong>8.5.2.</strong> These Terms of Usage are binding even if:- </p>
					<p>(a) the Company changes its name or constitution; or </p>
					<p>(b) the Company consolidates or amalgamates with another entity, in which case, that entity will substitute the Company in relation to these Terms of Usage and will continue in force between you and that entity. </p>
					<p><strong>8.5.3.</strong> You cannot assign or transfer your rights and obligations under these Terms of Usage without the Company&rsquo;s prior written permission. </p>
					<p><strong>8.6. Applicable Law and Proceedings </strong></p>
					<p><strong>8.6.1.</strong> These Terms of Usage are governed by and will be interpreted according to the laws of Malaysia. </p>
					<p><strong>8.6.2.</strong> You agree to irrevocably submit to the exclusive jurisdiction of the courts of Malaysia which means that legal proceedings against us can only be brought in the courts of Malaysia. This clause does not limit the Company&rsquo;s right to bring legal proceedings in any country and to take concurrent legal proceedings in more than one country. </p>
					<p><strong>8.7 Suspension or Termination of AEON Wallet or AEON Pay </strong></p>
					<p><strong>8.7.1</strong> The Company reserves the right to suspend or terminate usage of the AEON Wallet application or AEON Pay service for any reason at our sole and absolute discretion, subject to providing 21 days prior notice to you. </p>
					<p><strong>9. Updates to AEON Wallet Application Software</strong></p>
					<p><strong>9.1.</strong> AEON Wallet may be updated from time to time to a revised/new version and you are required to perform such update of the application software in your Device to ensure full performance and functionality of AEON Wallet. The Company shall not be responsible for any loss or damage resulting from any failure by you to update to the latest version of AEON Wallet.</p>
					<p><strong>10. Privacy Policy</strong></p>
					<p><strong>10.1</strong> You hereby confirm that you have read, understood and agreed to be bound by the AEON Credit Privacy Notice (which is available at <a href="http://www.aeoncredit.com.my">www.aeoncredit.com.my</a>). You agree that by using the AEON Wallet, you are giving consent to AEON Credit for the information collected by AEON Credit from you to be used and/or disclosed in accordance to the Company&rsquo;s Privacy Policy and the Personal Data Protection Act 2010. For the avoidance of doubt, you agree that the said Privacy Notice shall be deemed to be incorporated by reference into this Terms of Usage.</p>
					<p><strong>11. Definitions and Interpretation </strong></p>
					<p><strong>11.1.</strong> For the purpose of these Terms and Conditions, the following terms shall, unless the context otherwise requires, have the meanings as defined below. All other terms not defined herein shall have the meaning as may generally be accepted within the industry based on the context used herein: </p>
					<p><strong>11.1.1.</strong> &ldquo;Account&rdquo; refers to any account you now or hereafter have with the Company and any account used for the purposes of the AEON Wallet and from which funds may be applied for the utilisation of AEON Pay. </p>
					<p><strong>11.1.2.</strong> &ldquo;Card&rdquo; means any Principal or Supplementary credit card, prepaid card or loyalty programme/membership card issued by AEON Credit to you, but excluding any card which has been terminated, cancelled or blocked from usage by AEON Credit. </p>
					<p><strong>11.1.3.</strong> &ldquo;Device&rdquo; means any compatible smartphone or mobile device used by you to access and use the AEON Wallet. </p>
					<p><strong>11.1.4.</strong> &ldquo;Liability&rdquo; means, all debts, liabilities or obligations you owe to the Company now or in future, whether actual or contingent, primary or collateral, several or joint. Loss includes claims, actions, losses, damages, demands, liabilities and costs of any kind. </p>
					<p><strong>11.1.5.</strong> &ldquo;Microsite&rdquo; refers to the website hosted by AEON Credit for the purpose of providing additional security for managing AEON Wallet installation on a different device.</p>
					<p><strong>11.1.6. </strong>&ldquo;PIN&rdquo; means the Personal Identification Number (PIN) or similar access code/password chosen by you which is used to confirm your identity when accessing the AEON Wallet or specific services/functions in the AEON Wallet. </p>
					<p><strong>11.1.7.</strong> &ldquo;AEON Wallet&rdquo; refers to an application which provides service including but not limited to online account or card management, payment card services and loyalty/membership card services through the medium of a compatible smartphone or mobile device. </p>
					<p><strong>11.1.8.</strong> &ldquo;AEON Pay&rdquo; refers to the function of AEON Wallet which allows you to make payments using the mobile Device. </p>
					<p><strong>11.1.9.</strong> &ldquo;You&rdquo; or &ldquo;your&rdquo; refers to potential and existing users of AEON Wallet;</p>
					<p><strong>11.1.10.</strong> &ldquo;The Company&rdquo; or &ldquo;AEON Credit&rdquo; refers to AEON Credit and shall include its successors-in-title and permitted assigns. </p>
					<p><strong>12. Further Enquiries and Assistance </strong></p>
					<p>Please contact AEON Credit if you have any questions related to these Terms of Usage or require any assistance related to the AEON Wallet :</p>
					<p><strong>Customer Care Department</strong></p>
					<p><strong>AEON Credit Service (M) Berhad</strong> <br /> </p>
					<p>Tel:&nbsp;+603 2719 9999&nbsp;<br /> Email:&nbsp;customerservice@aeoncredit.com.my</p>
				</div>
			</div>
		);
	}
}